services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 'app:create_app()'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:2004@host.docker.internal:5432/Place-Pulse
